//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<int> LoaiSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string Mota { get; set; }
    }
}
